services:
  news-bot-app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    container_name: news-bot-app
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    restart: always